# mode training
load_checkpoint : False

# Algortihm Parameters
alpha           : 0.0   # discount constant
gamma           : 1  # discount factor
epsilon         : 0.9 # exploration constant
epsilon_final   : 0.05
epsilon_decay   : 1000000

save_fre        : 100

update_fre      : 100
n_episodes      : 2000
n_steps         : 1000
avg_err_fre     : 50

learning_rate   : 0.01
mem_size        : 50000
batch_size      : 64

# mode_optimize   : 'normal_dqn'
# mode_optimize   : 'dqn_replay_memory'
mode_optimize   : 'dqn_taget_net'
# mode_optimize   : 'dueling_dqn'

# loss_func       : 'MSE_loss'
loss_func       : 'SmoothL1Loss'
clip_error      : True

# optimizer       : 'Adam'
optimizer       : 'RMS'

# activation      : 'Tanh'
activation      : 'ReLU'

# Environment Parameters
init_pose_file  : 'foot_chair.yaml'
# init_pose_file  : 'suitcase.yaml'
# init_pose_file  : 'ini_pose.yaml'

# Walk
step_num        : 10
step_time       : 0.5 # 1.0 # 0.5
step_length     : 0.1
side_step_length: 0.05
step_angle_deg  : 5

# State
angle_thresh    : 0.5 # desired imu_pitch (<=1.0)
fall_angle      : 10

# Action
# mode_action     : 'Discrete-Action'
mode_action     : 'Step-Action'
cob_x           : -0.015 # default
step_size       : 0.02   # cob_step

# Controller
controllers_list: [joint_state_controller, torso_y_position,     head_y_position,      head_p_position, 
                   l_arm_sh_p1_position,   l_arm_sh_r_position,  l_arm_sh_p2_position, l_arm_el_y_position, l_arm_wr_r_position, l_arm_wr_y_position, l_arm_wr_p_position, l_arm_grip_position, l_arm_grip_1_position,
                   r_arm_sh_p1_position,   r_arm_sh_r_position,  r_arm_sh_p2_position, r_arm_el_y_position, r_arm_wr_r_position, r_arm_wr_y_position, r_arm_wr_p_position, r_arm_grip_position, r_arm_grip_1_position,
                   l_leg_hip_y_position,   l_leg_hip_r_position, l_leg_hip_p_position, l_leg_kn_p_position, l_leg_an_p_position, l_leg_an_r_position,
                   r_leg_hip_y_position,   r_leg_hip_r_position, r_leg_hip_p_position, r_leg_kn_p_position, r_leg_an_p_position, r_leg_an_r_position]