big_suitcase:
  1:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 0.42
    r_arm_grip: 29.98
    r_arm_sh_p1: -19.33
    r_arm_sh_p2: -5.65
    r_arm_sh_r: -62.27
    r_arm_wr_p: 21.28
    r_arm_wr_r: -16.91
    r_arm_wr_y: 1.37
    time: 0
    velocity: 5
  2:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 29.13
    r_arm_grip: 8.62
    r_arm_sh_p1: 29.78
    r_arm_sh_p2: -49.59
    r_arm_sh_r: -79.1
    r_arm_wr_p: -45.73
    r_arm_wr_r: 74.05
    r_arm_wr_y: 55.36
    time: 0
    velocity: 5
  3:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 64.05
    r_arm_grip: 8.62
    r_arm_sh_p1: 31.05
    r_arm_sh_p2: -32.83
    r_arm_sh_r: -105.7
    r_arm_wr_p: -37.27
    r_arm_wr_r: 51.72
    r_arm_wr_y: 44.13
    time: 0
    velocity: 5
  4:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 64.06
    r_arm_grip: 55.0
    r_arm_sh_p1: 31.05
    r_arm_sh_p2: -32.84
    r_arm_sh_r: -105.69
    r_arm_wr_p: -37.27
    r_arm_wr_r: 51.72
    r_arm_wr_y: 44.13
    time: 0
    velocity: 5
black_chair:
  1:
    l_arm_el_y: -30.0
    l_arm_grip: 60.0
    l_arm_sh_p1: 25.0
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 30
    l_arm_wr_p: -0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 30.0
    r_arm_grip: 60.0
    r_arm_sh_p1: -25.0
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -30
    r_arm_wr_p: -0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: -0.0
    time: 0
    velocity: 5
  2:
    l_arm_el_y: -5.0
    l_arm_grip: 20.0
    l_arm_sh_p1: 3.5
    l_arm_sh_p2: 3.0
    l_arm_sh_r: -0.0
    l_arm_wr_p: -5.0
    l_arm_wr_r: 90.0
    l_arm_wr_y: 60.0
    r_arm_el_y: 5.0
    r_arm_grip: 20.0
    r_arm_sh_p1: -3.5
    r_arm_sh_p2: -3.0
    r_arm_sh_r: -0.0
    r_arm_wr_p: -5.0
    r_arm_wr_r: -90.0
    r_arm_wr_y: -60.0
    time: 0
    velocity: 5
  3:
    l_arm_el_y: 5.5
    l_arm_grip: 50.0
    l_arm_sh_p1: -22.0
    l_arm_sh_p2: 38.0
    l_arm_sh_r: 45.0
    l_arm_wr_p: -40.0
    l_arm_wr_r: 2.5
    l_arm_wr_y: 15.0
    r_arm_el_y: -5.5
    r_arm_grip: 49.93
    r_arm_sh_p1: 22.0
    r_arm_sh_p2: -38.0
    r_arm_sh_r: -45.0
    r_arm_wr_p: 40.0
    r_arm_wr_r: -2.5
    r_arm_wr_y: -15.0
    time: 0
    velocity: 5
black_heavy:
  1:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 30
    l_arm_wr_p: -0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 30.01
    r_arm_grip: 59.96
    r_arm_sh_p1: -24.99
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -30
    r_arm_wr_p: -0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: -0.0
    time: 0
    velocity: 10
  2:
    l_arm_el_y: -5.01
    l_arm_grip: 19.87
    l_arm_sh_p1: 3.51
    l_arm_sh_p2: 3.0
    l_arm_sh_r: -0.0
    l_arm_wr_p: -5.0
    l_arm_wr_r: 90.0
    l_arm_wr_y: 60.0
    r_arm_el_y: 5.01
    r_arm_grip: 19.96
    r_arm_sh_p1: -3.51
    r_arm_sh_p2: -2.99
    r_arm_sh_r: -0.0
    r_arm_wr_p: -5.0
    r_arm_wr_r: -90.0
    r_arm_wr_y: -60.0
    time: 0
    velocity: 10
  3:
    l_arm_el_y: 5.5
    l_arm_grip: 50.0
    l_arm_sh_p1: -22.0
    l_arm_sh_p2: 38.0
    l_arm_sh_r: 45.0
    l_arm_wr_p: -40.0
    l_arm_wr_r: -30
    l_arm_wr_y: 15.0
    r_arm_el_y: -5.5
    r_arm_grip: 49.93
    r_arm_sh_p1: 21.99
    r_arm_sh_p2: -38.01
    r_arm_sh_r: -45.0
    r_arm_wr_p: 40.0
    r_arm_wr_r: 30
    r_arm_wr_y: -15.0
    time: 0
    velocity: 10
blue_chair:
  1:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 0.42
    r_arm_grip: 29.98
    r_arm_sh_p1: -3.24
    r_arm_sh_p2: -5.64
    r_arm_sh_r: -62.27
    r_arm_wr_p: 21.28
    r_arm_wr_r: -16.91
    r_arm_wr_y: 1.37
    time: 0
    velocity: 10
  2:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 57.22
    r_arm_grip: 37.54
    r_arm_sh_p1: 28.71
    r_arm_sh_p2: -34.27
    r_arm_sh_r: -101.24
    r_arm_wr_p: -31.79
    r_arm_wr_r: -8.16
    r_arm_wr_y: -45.97
    time: 0
    velocity: 10
  3:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 57.09
    r_arm_grip: 15.3
    r_arm_sh_p1: 37.07
    r_arm_sh_p2: -33.23
    r_arm_sh_r: -102.67
    r_arm_wr_p: -23.58
    r_arm_wr_r: 3.75
    r_arm_wr_y: -35.55
    time: 0
    velocity: 5
  4:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 57.09
    r_arm_grip: 62.07
    r_arm_sh_p1: 37.09
    r_arm_sh_p2: -33.22
    r_arm_sh_r: -102.65
    r_arm_wr_p: -23.58
    r_arm_wr_r: 3.75
    r_arm_wr_y: -35.55
    time: 0
    velocity: 5
  5:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 57.22
    r_arm_grip: 56.62
    r_arm_sh_p1: 28.7
    r_arm_sh_p2: -34.26
    r_arm_sh_r: -101.23
    r_arm_wr_p: -31.79
    r_arm_wr_r: -8.16
    r_arm_wr_y: -45.97
    time: 0
    velocity: 5
heavy_suitcase:
  1:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 0.42
    r_arm_grip: 29.98
    r_arm_sh_p1: -3.24
    r_arm_sh_p2: -5.64
    r_arm_sh_r: -62.27
    r_arm_wr_p: 21.28
    r_arm_wr_r: -16.91
    r_arm_wr_y: 1.37
    time: 0
    velocity: 5
  2:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.01
    l_arm_wr_p: 0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 43.49
    r_arm_grip: 37.54
    r_arm_sh_p1: 28.71
    r_arm_sh_p2: -34.28
    r_arm_sh_r: -101.23
    r_arm_wr_p: -31.79
    r_arm_wr_r: -8.16
    r_arm_wr_y: -45.97
    time: 0
    velocity: 5
  3:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.01
    l_arm_wr_p: 0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 39.48
    r_arm_grip: 15.3
    r_arm_sh_p1: 37.06
    r_arm_sh_p2: -33.24
    r_arm_sh_r: -102.67
    r_arm_wr_p: -23.58
    r_arm_wr_r: 3.75
    r_arm_wr_y: -35.55
    time: 0
    velocity: 5
  4:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.01
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 39.48
    r_arm_grip: 55.74
    r_arm_sh_p1: 37.06
    r_arm_sh_p2: -33.23
    r_arm_sh_r: -102.65
    r_arm_wr_p: -23.59
    r_arm_wr_r: -5.7
    r_arm_wr_y: -35.54
    time: 0
    velocity: 5
  5:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 57.22
    r_arm_grip: 56.62
    r_arm_sh_p1: 28.7
    r_arm_sh_p2: -34.26
    r_arm_sh_r: -101.23
    r_arm_wr_p: -31.79
    r_arm_wr_r: -8.16
    r_arm_wr_y: -45.97
    time: 0
    velocity: 5
release:
  1:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 57.22
    r_arm_grip: 42.73
    r_arm_sh_p1: 28.7
    r_arm_sh_p2: -34.27
    r_arm_sh_r: -101.24
    r_arm_wr_p: -31.79
    r_arm_wr_r: -8.16
    r_arm_wr_y: -45.97
    time: 5
    velocity: 5
  2:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 0.42
    r_arm_grip: 29.98
    r_arm_sh_p1: -3.24
    r_arm_sh_p2: -5.64
    r_arm_sh_r: -62.27
    r_arm_wr_p: 21.28
    r_arm_wr_r: -16.91
    r_arm_wr_y: 1.37
    time: 0
    velocity: 10
  3:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 30.01
    r_arm_grip: 59.96
    r_arm_sh_p1: -24.99
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -74.99
    r_arm_wr_p: -0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: -0.0
    time: 0
    velocity: 10
release_human:
  1:
    l_arm_el_y: -64.0
    l_arm_grip: 10.0
    l_arm_sh_p1: -31.0
    l_arm_sh_p2: 33.0
    l_arm_sh_r: 100.0
    l_arm_wr_p: 37.0
    l_arm_wr_r: -50.0
    l_arm_wr_y: -45.0
    r_arm_el_y: 64.0
    r_arm_grip: 10.0
    r_arm_sh_p1: 31.0
    r_arm_sh_p2: -33.0
    r_arm_sh_r: -100.0
    r_arm_wr_p: -37.0
    r_arm_wr_r: 50.0
    r_arm_wr_y: 45.0
    time: 3
    velocity: 5
  2:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 30.01
    r_arm_grip: 59.96
    r_arm_sh_p1: -24.99
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -74.99
    r_arm_wr_p: -0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: -0.0
    time: 0
    velocity: 10
human_suitcase:
  1:
    l_arm_el_y: -0.5
    l_arm_grip: 30.0
    l_arm_sh_p1: 20.0
    l_arm_sh_p2: 5.5
    l_arm_sh_r: 62.0
    l_arm_wr_p: -21.5
    l_arm_wr_r: 17.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 0.5
    r_arm_grip: 30.0
    r_arm_sh_p1: -20.0
    r_arm_sh_p2: -5.5
    r_arm_sh_r: -62.0
    r_arm_wr_p: 21.5
    r_arm_wr_r: -17.0
    r_arm_wr_y: 0.0
    time: 0
    velocity: 10
  2:
    l_arm_el_y: -30.0
    l_arm_grip: 10.0
    l_arm_sh_p1: -30.0
    l_arm_sh_p2: 50.0
    l_arm_sh_r: 80.0
    l_arm_wr_p: 45.0
    l_arm_wr_r: -74.0
    l_arm_wr_y: -55.0
    r_arm_el_y: 30.0
    r_arm_grip: 10.0
    r_arm_sh_p1: 30.0
    r_arm_sh_p2: -50.0
    r_arm_sh_r: -80.0
    r_arm_wr_p: -45.0
    r_arm_wr_r: 74.0
    r_arm_wr_y: 55.0
    time: 0
    velocity: 10
  3:
    l_arm_el_y: -64.0
    l_arm_grip: 10.0
    l_arm_sh_p1: -31.0
    l_arm_sh_p2: 33.0
    l_arm_sh_r: 100.0
    l_arm_wr_p: 37.0
    l_arm_wr_r: -50.0
    l_arm_wr_y: -45.0
    r_arm_el_y: 64.0
    r_arm_grip: 10.0
    r_arm_sh_p1: 31.0
    r_arm_sh_p2: -33.0
    r_arm_sh_r: -100.0
    r_arm_wr_p: -37.0
    r_arm_wr_r: 50.0
    r_arm_wr_y: 45.0
    time: 0
    velocity: 5
  4:
    l_arm_el_y: -64.0
    l_arm_grip: 55.0
    l_arm_sh_p1: -31.0
    l_arm_sh_p2: 33.0
    l_arm_sh_r: 100.0
    l_arm_wr_p: 37.0
    l_arm_wr_r: -50.0
    l_arm_wr_y: -45.0
    r_arm_el_y: 64.0
    r_arm_grip: 55.0
    r_arm_sh_p1: 31.0
    r_arm_sh_p2: -33.0
    r_arm_sh_r: -100.0
    r_arm_wr_p: -37.0
    r_arm_wr_r: 50.0
    r_arm_wr_y: 45.0
    time: 0
    velocity: 5
standby:
  1:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 30.01
    r_arm_grip: 59.96
    r_arm_sh_p1: -24.99
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -74.99
    r_arm_wr_p: -0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: -0.0
    time: 0
    velocity: 10
suitcase:
  1:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 0.42
    r_arm_grip: 29.98
    r_arm_sh_p1: -3.24
    r_arm_sh_p2: -5.64
    r_arm_sh_r: -62.27
    r_arm_wr_p: 21.28
    r_arm_wr_r: -16.91
    r_arm_wr_y: 1.37
    time: 0
    velocity: 5
  2:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.01
    l_arm_wr_p: 0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 43.49
    r_arm_grip: 37.54
    r_arm_sh_p1: 28.71
    r_arm_sh_p2: -34.28
    r_arm_sh_r: -101.23
    r_arm_wr_p: -31.79
    r_arm_wr_r: -8.16
    r_arm_wr_y: -45.97
    time: 0
    velocity: 5
  3:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.01
    l_arm_wr_p: 0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 39.48
    r_arm_grip: 15.3
    r_arm_sh_p1: 37.06
    r_arm_sh_p2: -33.24
    r_arm_sh_r: -102.67
    r_arm_wr_p: -23.58
    r_arm_wr_r: 3.75
    r_arm_wr_y: -35.55
    time: 0
    velocity: 5
  4:
    l_arm_el_y: -30.01
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.98
    l_arm_sh_p2: 4.98
    l_arm_sh_r: 75.01
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    r_arm_el_y: 39.48
    r_arm_grip: 55.74
    r_arm_sh_p1: 37.06
    r_arm_sh_p2: -33.23
    r_arm_sh_r: -102.65
    r_arm_wr_p: -23.59
    r_arm_wr_r: -5.7
    r_arm_wr_y: -35.54
    time: 0
    velocity: 5
  5:
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 24.99
    l_arm_sh_p2: 4.99
    l_arm_sh_r: 75.0
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: 57.22
    r_arm_grip: 56.62
    r_arm_sh_p1: 28.7
    r_arm_sh_p2: -34.26
    r_arm_sh_r: -101.23
    r_arm_wr_p: -31.79
    r_arm_wr_r: -8.16
    r_arm_wr_y: -45.97
    time: 0
    velocity: 5
