left_arm:
  P1:
    cx: 59.0
    cy: 404.0
    ik_x: 0.25
    ik_y: 0.28
  P2:
    cx: 74.0
    cy: 157.0
    ik_x: 0.55
    ik_y: 0.34
  P3:
    cx: 378.0
    cy: 157.0
    ik_x: 0.55
    ik_y: -0.05
  P4:
    cx: 356.0
    cy: 404.0 #395.0
    ik_x: 0.25
    ik_y: -0.02
right_arm:
  P1:
    cx: 596.0
    cy: 405.0
    ik_x: 0.25
    ik_y: -0.28
  P2:
    cx: 589.0
    cy: 158.0
    ik_x: 0.55
    ik_y: -0.34
  P3:
    cx: 287.0
    cy: 151.0
    ik_x: 0.55
    ik_y: 0.05
  P4:
    cx: 302.0
    cy: 405.0 # 387.0
    ik_x: 0.25
    ik_y: 0.02
